import XCTest
@testable import StatusTrioCore

final class SystemPowerReaderTests: XCTestCase {
    // Captured AppleSMC wire layout: 80-byte response, key info at 28/32,
    // firmware result at 40 and payload at 48. Fixtures are literal, not
    // generated by the production encoder/decoder they are meant to check.
    private func info(type: [UInt8] = [0x20, 0x74, 0x6c, 0x66], size: UInt8 = 4) -> [UInt8] {
        var bytes = [UInt8](repeating: 0, count: 80)
        bytes[28] = size
        bytes.replaceSubrange(32..<36, with: type)
        return bytes
    }

    private func value(_ payload: [UInt8]) -> [UInt8] {
        var bytes = [UInt8](repeating: 0, count: 80)
        bytes.replaceSubrange(48..<(48 + payload.count), with: payload)
        return bytes
    }

    private func read(info: [UInt8], value: [UInt8]) -> Double? {
        SystemPowerReader.readWatts { request in request[42] == 9 ? info : value }
    }

    func testReadsSystemTotalInWattsUsingOnlyReadCommands() throws {
        var commands: [UInt8] = []
        let watts = SystemPowerReader.readWatts { request in
            XCTAssertEqual(request.count, 80)
            XCTAssertEqual(Array(request.prefix(4)), [0x52, 0x54, 0x53, 0x50], "Read PSTR, not a battery rail")
            commands.append(request[42])
            if request[42] == 9 { return self.info() }
            XCTAssertEqual(request[42], 5, "Only read-key-info and read-bytes are allowed")
            XCTAssertEqual(Array(request[28..<32]), [4, 0, 0, 0])
            return self.value([0, 0, 0x8a, 0x41]) // Float32 17.25 W, little endian
        }
        XCTAssertEqual(try XCTUnwrap(watts), 17.25)
        XCTAssertEqual(commands, [9, 5])
    }

    func testDecodesFixedPointPowerWithoutLosingFractionalWatts() throws {
        XCTAssertEqual(try XCTUnwrap(read(info: info(type: [0x32, 0x65, 0x70, 0x66], size: 2),
                                             value: value([0, 69]))), 17.25) // fpe2
        XCTAssertEqual(try XCTUnwrap(read(info: info(type: [0x38, 0x37, 0x70, 0x73], size: 2),
                                             value: value([17, 64]))), 17.25) // sp78
    }

    func testUnavailableAndMalformedRepliesNeverBecomeZeroWatts() {
        XCTAssertNil(SystemPowerReader.readWatts { _ in nil })
        var firmwareError = info()
        firmwareError[40] = 0x84
        for invalidInfo in [[], Array(info().dropLast()), firmwareError,
                            info(size: 0), info(size: 33), info(size: 2),
                            info(type: [0, 0, 0, 0])] {
            XCTAssertNil(read(info: invalidInfo, value: value([0, 0, 0x8a, 0x41])))
        }
        var failedValue = value([0, 0, 0x8a, 0x41])
        failedValue[40] = 0x84
        for invalidValue in [[], failedValue,
                             value([0, 0, 0, 0]), // no sensor reading
                             value([0, 0, 0x80, 0xbf]), // -1
                             value([0, 0, 0x80, 0x7f]), // infinity
                             value([0, 0, 0xc0, 0x7f])] { // NaN
            XCTAssertNil(read(info: info(), value: invalidValue))
        }
        XCTAssertNil(read(info: info(type: [0x38, 0x37, 0x70, 0x73], size: 2), value: value([255, 0])))
    }
}
